name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Build poppler
        run: |
          make distribution
      - name: Upload the artifacts
        uses: actions/upload-artifact@v1
        with:
          name: poppler
          path: export/poppler.zip
      - name: Publish the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'export/poppler.zip'
